Update version

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -33,9 +33,10 @@ jobs:
         flutter pub run pigeon --input pigeons/messages.dart
     
     - name: Analyze
-      run: flutter analyze . || exit $(( $? == 1 ? 0 : $? ))
-      # This command runs Flutter analyze and exits with 0 if there are only warnings or infos,
-      # allowing the workflow to continue. It will still fail on actual errors.
+      run: |
+        # This command runs Flutter analyze and exits with 0 if there are only warnings or infos,
+        # allowing the workflow to continue. It will still fail on actual errors.
+        flutter analyze . || exit $(( $? == 1 ? 0 : $? ))
     
     - name: Setup Ruby
       uses: ruby/setup-ruby@v1
